name: Main Github Actions
on:
  workflow_dispatch:
  push:
    branches:
      - 'main' # (main branch) Set branch of the GH repo to push
jobs:
  test_suite: # Name of the job
      runs-on: ubuntu-20.04 # Choosing OS
      steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.9.1' # In command line run “node -v” and choose your version
      - run: npm ci
     # - run: npm config set script-shell "G:\Git\bin\bash.exe"
      - name: run test
        run: npm run test:headless # Our name of the headless script
      - name: Copy History
        if: always()
        run: cp -r $(pwd)/docs/history/. $(pwd)/allure-results/history
      - name: Generate Report
        if: always()
        run: npm run allure:generate # Name of the allure generate script
      - env:
          API_TOKEN_GITHUB: ${{ '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' }} # Instruction where to get token is below
        with:
          source-directory: 'docs'
          destination-github-username: 'irunnie' # Your username
          destination-repository-name: 'ghactoions2' # Name of your repo
          user-email: irunne@gmail.com # Your email
          target-branch: main
